# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5e3a93f6edc8fdd6b486152caadab38e43a381485efaae9f8b77986f795112a7f4ee4f148970c94cfdc780564b2ac95b240d42b0ffe31e75cd58647f654adea

test:
  secret_key_base: 1fddf9535bb99d95b76d653e677ef60abfbad21aa847625797cfd9eb9ca0c03f928ad1e45300b625a00aa00957e97d2c95008d3e4307ccee5e22c1aee5f42e77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
